### ISSUE TITLE
revision 0 causes problems in SvnRepo.pdiff()

### ISSUE THREAD

**Issue by OEP** [ScottDuckworth/python-anyvcs#15]
Calling pdiff() on revision 0 raises a CalledProcessError. This is sort of troublesome since it shows up as a parent of revision 1 and there's not a vcs-agnostic way of checking if all parents are valid inputs to pdiff().

I've got a branch over on my fork you can [compare](https://github.com/OEP/python-anyvcs/compare/ScottDuckworth:develop...fix-svn-0-revision?expand=1) that seeks to remove revision 0 from the API if you like. It passes unit tests, though I don't think it removes the 0 revision in all usages of log(). At that, I'm not even sure removing revision 0 from the API is the right thing to do.

**Comment by ScottDuckworth** [comment]
I'm thinking the most graceful solution will be to return an empty diff.
