### ISSUE TITLE
cache VCSRepo.log() results for speed improvements

### ISSUE THREAD

**Issue by ScottDuckworth** [ScottDuckworth/python-anyvcs#21]
Cache entries should be versioned to accommodate for changes in CommitLogEntry's API.  Cache files should be dbm files where keys are canonical revision strings and values are JSON strings containing all properties of CommitLogEntry in addition to a single 'v' key representing the version.

The cache should be used when revrange is a single revision, and optionally in other cases.  The cache should be updated when possible if there is not already a cache entry for that revision.

**Comment by OEP** [comment]
You may have looked already, but [Shelves](http://docs.python.org/2/library/shelve.html) may be worth a look too since they are a part of the standard library, but the JSON representation could have its advantages were anyvcs used in a web API.

**Comment by ScottDuckworth** [comment]
I had considered shelves but I found that python's json implementation is faster than even cPickle (which is much faster than pickle, which is used by shelve): http://kovshenin.com/2010/pickle-vs-json-which-is-faster/

Plus, json is portable and pickle is specific to python.
