### ISSUE TITLE
GitRepo.empty() is an expensive call at the top of GitRepo.log()

### ISSUE THREAD

**Issue by OEP** [ScottDuckworth/python-anyvcs#25]
I've been trying to find where all the time goes in the single revision lookups and it looks like the call to empty() at the top of GitRepo.log() is pretty expensive (at least when repeated many times). In my test script it looks like we can reclaim over a second on the "ls the root of git" benchmark if we either cache that result or find some way to make it really cheap.

**Comment by ScottDuckworth** [comment]
Implemented in 7c5e3b0. And yes, it dramatically speeds it up - in my case from 1.233s to 0.112s. Good catch, Paul!
