### ISSUE TITLE
encoding/decoding issues

### ISSUE THREAD

**Issue by ScottDuckworth** [ScottDuckworth/python-anyvcs#33]
Adapting the code for Python 3 required using str.encode() and bytes.decode().  This may have unintended consequences in Python 2, and also makes the invalid assumption that the default encoding is always used.  Commit logs, file names, and file contents may use different encodings.  In the case of file contents returned by cat(), it may make sense to return the un-decoded data (bytes in Python 3, str in Python 2).

**Comment by ScottDuckworth** [comment]
There is at least one case where the current approach is causing issues.  On the official git repository, a log() on revision ddeaf7ef0d23519cb810542978da54dd89d6fb73 raises a UnicodeDecodeError.

**Comment by OEP** [comment]
One thing that could be done is add a 'decode' arg to VCSRepo._command, and:
- if it is None, do no decoding
- if it is a 0,1,2-tuple, use those as the args to str/bytes.decode()

then you can decide whether or not you open that part up on a per API call basis. cat() currently won't work with binary stuff but I made the described change to do some work on buffet.

**Comment by ScottDuckworth** [comment]
3d81c30b199cf15b11ce57a0eaab579643bd50ba provides an initial attempt at doing this for git.  To keep the API simple, I've just added a class property `encoding` that defaults to utf-8.  Also, I'm mostly using the [replace](http://docs.python.org/3.1/library/codecs.html#codec-base-classes) policy when encountering encoding errors.
