### ISSUE TITLE
Some spec disagreement on meaning of SvnRepo.empty()

### ISSUE THREAD

**Issue by OEP** [ScottDuckworth/python-anyvcs#34]
From the documentation of VCSRepo.empty():

```
Test if the repository contains any commits
```

This seems to imply len(VCSRepo.log()) == 0, but actually it's not the case with SvnRepo because of that darn r0. That assumption caused me to run into a problem with buffet, but I think I can technically work around it without doing any SVN-specific stuff.

In the meantime is there some way we can clear this up?

**Comment by OEP** [comment]
Actually, I am having trouble reproducing all of a sudden. Let me figure out what's wrong.

EDIT: OK, I figured out the actual problem

**Comment by ScottDuckworth** [comment]
Is there something that needs to be fixed with python-anyvcs?

**Comment by OEP** [comment]
This sort of illustrates the problem:

```
>>> import anyvcs
>>> svn = anyvcs.open('svn/main')
>>> git = anyvcs.open('git/main')
>>> hg = anyvcs.open('hg/main')
>>> svn.empty()
True
>>> git.empty()
True
>>> hg.empty()
True
>>> len(svn.log())
1
>>> len(git.log())
0
>>> len(hg.log())
0
```

I guess that's sort of a necessity since r0 is used in other places in the API, but maybe the documentation of VCSRepo.empty() needs to be updated to reflect this.
